version: '3.7'

services:
  api:
    image: leandro2r/docker-class:0.0.1
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.master == true
    networks: &cluster
      - net_class
    environment:
      - DB_HOST=elastic
      - DB_PORT=9200
      - TRIES=10
    # command: "tail -f /dev/null"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.master == true
    networks: *cluster
    environment:
      - TZ=America/Sao_Paulo
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - node.name={{.Node.Hostname}}_{{.Service.Name}}
    # ports:
    #   - 9200:9200

  kibana: 
    image: docker.elastic.co/kibana/kibana:6.3.2
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.slave == true
    networks: *cluster
    environment:
      - TZ=America/Sao_Paulo
      - XPACK_SECURITY_ENABLED=false
    volumes:
      - ~/docker-class/kibana/config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 80:5601

networks:
  net_class:
    driver: overlay
